"""Cover page generator for PDF reports."""
from __future__ import annotations
from typing import Any

try:
    from reportlab.lib import colors
    from reportlab.lib.units import mm
    from reportlab.lib.enums import TA_CENTER
    from reportlab.platypus import Paragraph, Spacer, Table, TableStyle, HRFlowable
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False

from .pdf_styles import *
from .pdf_templates import make_score_card
from .report_metadata import ReportMetadata


def build_cover_page(metadata: ReportMetadata, overall_score: float = 0, quality: str = 'N/A'):
    story = []
    story.append(Spacer(1, 40*mm))
    # Title
    story.append(Paragraph('<b>Architectural Design Report</b>', ParagraphStyle('ct', fontSize=28, textColor=COLOR_PRIMARY, alignment=TA_CENTER, spaceAfter=8)))
    story.append(Paragraph(metadata.project_name, ParagraphStyle('cp', fontSize=20, textColor=COLOR_DARK, alignment=TA_CENTER, spaceAfter=20)))
    # Divider
    story.append(HRFlowable(width='80%', thickness=2, color=COLOR_ACCENT, spaceBefore=10, spaceAfter=20, hAlign='CENTER'))
    # Info table
    info_data = [
        ['Generated by', metadata.generated_by],
        ['Date', metadata.generated_at[:10] if metadata.generated_at else ''],
        ['Revision', metadata.revision],
        ['Engine Version', metadata.engine_version],
        ['Craftshood AI Version', metadata.craftshood_version],
    ]
    if metadata.author:
        info_data.append(['Author', metadata.author])
    if metadata.organization:
        info_data.append(['Organization', metadata.organization])
    info_table = Table(info_data, colWidths=[CONTENT_WIDTH*0.4, CONTENT_WIDTH*0.4])
    info_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('TEXTCOLOR', (0, 0), (0, -1), COLOR_GRAY),
        ('TEXTCOLOR', (1, 0), (1, -1), COLOR_DARK),
        ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
        ('ALIGN', (1, 0), (1, -1), 'LEFT'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 20*mm))
    # Score card
    if overall_score > 0:
        story.append(make_score_card('Overall Design Score', overall_score, [('Quality', quality)]))
    story.append(Spacer(1, 30*mm))
    # Logo placeholder
    story.append(Paragraph('<i>Craftshood AI</i>', ParagraphStyle('logo', fontSize=12, textColor=COLOR_GRAY, alignment=TA_CENTER)))
    return story
