"""PDF layout templates and reusable components."""
from __future__ import annotations

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    from reportlab.platypus import Table, TableStyle, Paragraph, Spacer, PageBreak, HRFlowable
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False

from .pdf_styles import *


def header_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(COLOR_GRAY)
    # Header
    canvas.drawString(MARGIN, PAGE_HEIGHT - 10*mm, 'Craftshood AI - Architectural Report')
    canvas.drawRightString(PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 10*mm, doc.title if hasattr(doc, 'title') else 'Report')
    # Footer
    canvas.drawString(MARGIN, 10*mm, 'Generated by Craftshood AI')
    canvas.drawRightString(PAGE_WIDTH - MARGIN, 10*mm, f'Page {doc.page}')
    # Line
    canvas.setStrokeColor(COLOR_LIGHT_GRAY)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, PAGE_HEIGHT - 13*mm, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 13*mm)
    canvas.line(MARGIN, 13*mm, PAGE_WIDTH - MARGIN, 13*mm)
    canvas.restoreState()


def make_score_card(title, score, items=None):
    if items is None:
        items = []
    color = COLOR_SUCCESS if score >= 85 else COLOR_SECONDARY if score >= 70 else COLOR_WARNING if score >= 50 else COLOR_DANGER
    data = [[Paragraph(f'<b>{title}</b>', ParagraphStyle('th', fontSize=11, textColor=COLOR_DARK)), Paragraph(f'<b>{score:.0f}</b>', ParagraphStyle('ts', fontSize=14, textColor=color, alignment=TA_CENTER))]]
    for label, val in items:
        data.append([Paragraph(label, ParagraphStyle('tl', fontSize=9, textColor=COLOR_GRAY)), Paragraph(str(val), ParagraphStyle('tv', fontSize=9, textColor=COLOR_DARK))])
    t = Table(data, colWidths=[CONTENT_WIDTH * 0.6, CONTENT_WIDTH * 0.4])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f8f9fa')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#fafbfc')]),
        ('GRID', (0, 0), (-1, -1), 0.5, COLOR_LIGHT_GRAY),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ]))
    return t


def make_data_table(headers, data, col_widths=None):
    header_style = ParagraphStyle('th', fontSize=9, textColor=COLOR_WHITE, alignment=TA_CENTER)
    cell_style = ParagraphStyle('tc', fontSize=8, textColor=COLOR_DARK)
    header_row = [Paragraph(h, header_style) for h in headers]
    table_data = [header_row]
    for row in data:
        table_data.append([Paragraph(str(c), cell_style) for c in row])
    if col_widths is None:
        col_widths = [CONTENT_WIDTH / len(headers)] * len(headers)
    t = Table(table_data, colWidths=col_widths)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), COLOR_PRIMARY),
        ('TEXTCOLOR', (0, 0), (-1, 0), COLOR_WHITE),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8f9fa')]),
        ('GRID', (0, 0), (-1, -1), 0.5, COLOR_LIGHT_GRAY),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    return t


def make_section_title(text):
    return Paragraph(f'<b>{text}</b>', ParagraphStyle('sh', fontSize=16, textColor=COLOR_PRIMARY, spaceBefore=10, spaceAfter=6))


def make_divider():
    return HRFlowable(width='100%', thickness=1, color=COLOR_LIGHT_GRAY, spaceBefore=6, spaceAfter=6)
